/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hql_CONSTANTS_H
#define hql_CONSTANTS_H

#include "hql_types.h"

namespace Hypertable { namespace ThriftGen {

class hqlConstants {
 public:
  hqlConstants();

};

extern const hqlConstants g_hql_constants;

}} // namespace

#endif
