/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hql_constants.h"

namespace Hypertable { namespace ThriftGen {

const hqlConstants g_hql_constants;

hqlConstants::hqlConstants() {
}

}} // namespace

