/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hypertable.ThriftGen
{
  /// <summary>
  /// State flags for a key
  /// 
  /// Note for maintainers: the definition must be sync'ed with FLAG_* constants
  /// in src/cc/Hypertable/Lib/Key.h
  /// 
  /// DELETE_ROW: row is pending delete
  /// 
  /// DELETE_CF: column family is pending delete
  /// 
  /// DELETE_CELL: key is pending delete
  /// 
  /// DELETE_CELL_VERSION: delete specific timestamped version of key
  /// 
  /// INSERT: key is an insert/update (default state)
  /// </summary>
  public enum KeyFlag
  {
    DELETE_ROW = 0,
    DELETE_CF = 1,
    DELETE_CELL = 2,
    DELETE_CELL_VERSION = 3,
    INSERT = 255,
  }
}
